allowBuilds:
    "@parcel/watcher": true
    sharp: true
    simple-git-hooks@2.14.0: true
    unrs-resolver: true

configDependencies:
    "@obusk/pnpm-plugin-defaults": 0.6.4

minimumReleaseAgeExclude:
    - "@next/*"
    - next
    - react
    - react-dom
    - eslint-config-next
    - "@obusk/eslint-config-next"

overrides:
    "@types/react": 19.2.18
    "@types/react-dom": 19.2.7
    # https://github.com/oBusk/npm-diff.app/pull/1046
    "@npmcli/agent@^5": ^4.0.2

patchedDependencies:
    gitdiff-parser@0.3.1: patches/gitdiff-parser@0.3.1.patch

trustPolicyExclude:
    - semver@6.3.1
    - eslint-import-resolver-typescript@3.10.1
