allowBuilds:
    sharp: true
    simple-git-hooks@2.13.1: true
    unrs-resolver: true

configDependencies:
    "@obusk/pnpm-plugin-defaults": 0.4.0+sha512-aSq4PaHkxHRExXx1n3Cv1o7iAeUDRC1x3cOldp3q36acVfmOg3hgWKBNAzhCkRiy04xCQOU43Lh5xQJZmPc/hQ==

minimumReleaseAgeExclude:
    - "@next/*"
    - next
    - react
    - react-dom
    - eslint-config-next
    - "@obusk/eslint-config-next"

overrides:
    "@types/react": 19.2.14
    "@types/react-dom": 19.2.3

trustPolicyExclude:
    - semver@6.3.1
    - tailwind-merge@2.6.1
    - eslint-import-resolver-typescript@3.10.1
