allowBuilds:
    sharp: true
    simple-git-hooks@2.13.1: true
    unrs-resolver: true

configDependencies:
    "@obusk/pnpm-plugin-defaults": 0.3.0+sha512-Vc6B0IfZgB+ydRh0eYpmxV7eCEC5fjDcKX+WrpSd3NiIaFS7yLrXRaWVSoIOLvAYIKbcsYXUa+ZFCf5zVw3nSw==

minimumReleaseAgeExclude:
    - "@next/*"
    - next
    - react
    - react-dom
    - eslint-config-next
    - "@obusk/eslint-config-next"

overrides:
    "@types/react": 19.2.10
    "@types/react-dom": 19.2.3

trustPolicyExclude:
    - semver@6.3.1
    - tailwind-merge@2.6.1
    - eslint-import-resolver-typescript@3.10.1
