configDependencies:
    "@obusk/pnpm-plugin-defaults": 0.1.0+sha512-vsCchpE+K6g67YdDYYBCVQQFpfVFuVV423CCBbUEBm7FmWg/MI0Keuhkb6bjWpWaITE1PMSmcsrXbHv9FPFloA==

minimumReleaseAgeExclude:
    - "@next/*"
    - next
    - react
    - react-dom

onlyBuiltDependencies:
    - sharp
    - simple-git-hooks
    - unrs-resolver

trustPolicyExclude:
    - semver@6.3.1
    - tailwind-merge@2.6.0
    - undici-types@6.21.0
    - eslint-import-resolver-typescript@3.10.1

hoistPattern:
    - eslint-plugin-react-hooks
    - "@next/eslint-plugin-next"
