configDependencies:
    "@obusk/pnpm-plugin-defaults": 0.1.0+sha512-vsCchpE+K6g67YdDYYBCVQQFpfVFuVV423CCBbUEBm7FmWg/MI0Keuhkb6bjWpWaITE1PMSmcsrXbHv9FPFloA==

onlyBuiltDependencies:
    - simple-git-hooks

trustPolicyExclude:
    - semver@6.3.1
    - tailwindcss@3.4.18
