configDependencies:
    "@obusk/pnpm-plugin-defaults": 0.2.0+sha512-3oufTLQAL1SDdQ9iA5hLRnZjnBnU9uIEOBcwCKRtS+F6NyJphTq6RMIpaZgostZjQRHUaNbGSg6B2gn91drCSQ==

minimumReleaseAgeExclude:
    - "@next/*"
    - next
    - react
    - react-dom
    - eslint-config-next
    - "@obusk/eslint-config-next"

onlyBuiltDependencies:
    - sharp
    - simple-git-hooks
    - unrs-resolver

overrides:
    "@types/react": 19.2.7
    "@types/react-dom": 19.2.3

trustPolicyExclude:
    - semver@6.3.1
    - tailwind-merge@2.6.0
    - undici-types@6.21.0
    - eslint-import-resolver-typescript@3.10.1
