name: Node.js CI
permissions:
    contents: read

on: [push, pull_request]

jobs:
    lint:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        env:
            CI: true

        steps:
            - name: Checkout
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
            - name: Set up using pnpm
              uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
              with:
                  standalone: true
                  run_install: true
                  cache: true
            - name: Check Linting
              run: pnpm run lint

    test:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        env:
            CI: true

        steps:
            - name: Checkout
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

            - name: Set up using pnpm
              uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
              with:
                  standalone: true
                  run_install: true
                  cache: true
            - name: Run tests
              run: pnpm run test-ci

    typecheck:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        env:
            CI: true

        steps:
            - name: Checkout
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
            - name: Set up using pnpm
              uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
              with:
                  standalone: true
                  run_install: true
                  cache: true
            - name: Type check
              run: pnpm run typecheck

    build:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        env:
            CI: true

        steps:
            - name: Checkout
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
            - name: Set up using pnpm
              uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
              with:
                  standalone: true
                  run_install: true
                  cache: true
            - name: Build
              run: pnpm run build
